:sectnums:
:sectanchors:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:icons: font
:toc:
:sectlinks:
:toc-placement!:
:toc-title: pass:[<h3>Table of Contents</h3>]

= HiveMQ Client Command Line Interface

**HiveMQ-CLI** is the official HiveMQ MQTT 5.0 and MQTT 3.1.1 compatible command line interface for MQTT clients which uses the https://github.com/hivemq/hivemq-mqtt-client[HiveMQ MQTT Client API].

If you have any questions feel free to open https://github.com/hivemq/hivemq-cli/issues/new[a new GitHub issue].
You can follow the development progress of HiveMQ-CLI on https://github.com/hivemq/hivemq-cli/projects[the GitHub Projects Section].

toc::[]

== Main Features

* Support of the main MQTT client methods: *subscribe*, *publish*, *connect*, *disconnect*
* Interactive shell for client connection handling
* MQTT 3.1.1 and MQTT 5.0 support
* SSL/TLS support
* Authentication

== Installation

WARNING: As latency-issues may slow down the CLI under **Mac OS X** please verify that you have the entry ``127.0.0.1 localhost your-pc-name`` specified under ``/etc/hosts``.
You can use ``sudo sh -c "echo 127.0.0.1 localhost $(hostname) >> /etc/hosts"`` to append this configuration to your hosts file.

=== Prerequisites

At least Java 8 is required to run HiveMQ-CLI.

The CLI was written in the https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html[11.0.4 Java release] which is the preferred version to run this project.

=== Installation using a package manager

For *Mac OS X* and *Linux* systems use https://brew.sh/[Homebrew] to install HiveMQ-CLI via the https://github.com/hivemq/homebrew-hivemq-cli[HiveMQ-CLI Tap].

```
$ brew tap hivemq/hivemq-cli
```

```
$ brew install hivemq-cli
```

NOTE: As the current tap repository is still a private repository please follow https://gist.github.com/mlafeldt/8e7d50ee0b1de44e256d[this guide] if you face any authentication problems.

== Usage

=== Synopsis

```
$ hivemq-cli [flags] [METHOD] [OPTION [OPTION]]
```

Supported methods:

* <<Connect>> (Used for Publish / Subscribe)
* <<Publish>>
* <<Subscribe>>
* <<Shell>>


See also ``hivemq-cli --help``.

=== Examples

Basic Publish:

```
$ hivemq-cli pub -t topic -m "Hello World"
```

Basic Subscribe (will block the console to output published mesages):

```
$ hivemq-cli sub -t topic
>
```

Interactive Shell:

```
$ hivemq-cli shell
hmq>
```

Connect client with identifier in shell

```
hmq> con -i hmqShell -h localhost
```

== Connect

NOTE: Connect builds the basic wrapper of the publish and subscribe commands.
Therefore all Connect Options can also be used in publish and subscribe.

NOTE: This method is only accessible in Shell-Mode

The Connect method creates a client and connects it to the specified broker.
The client will stay connected until it is disconnected by the broker or the <<Disconnect>> method is called.
To list all of the connected clients use the <<List>> method.

=== Simple Examples

|===
|Command |Explanation

| ``hmq> con ``
| Creates and connect a new MQTT client with the default settings

| ``hmq> con -v 3 -h myHost``
| Creates and connects an MQTT 3.1.1 client at myHost with the default port

| ``hmq> con -i hmq-client -p 1884``
| Creates and connects an MQTT client at localhost with port 1884 which is identified by "hmq-client".
|===

See also ``hivemq-cli con --help``

=== Synopsis

```
hmq> con {  [-h <hostname>]
            [-V <mqtt-version>]
            [-p <port-number>]
            [-i <client-identifier>]
            [-d <debug>]
            [-v <verbose>]
            [-u <username>]
            [-P <password>]
            [-c <clean-session>]
            [-s <use-default-ssl>]
            [-e <session-expiry>]
            [-wt <will-message-topic>]
            [-wq <will-quality-of-service>]
            [-wm <will-message-payload>]
            [-wr <will-retain>]
            [-we <will-expiry>]
            [-wd <will-delay-interval>]
            [-wp <will-payload-format>]
            [-wc <will-content>]
            [-wrt <will-response-topic>]
            [-wcd <will-correlation-data>]
            [-wu <will-user-properties>]
            [--cafile <path-to-certificate>]
            [--capath <path-to-certificate-directory>]
            [--ciphers <tls-ciphersuites>]
            [--tls-version <tls-version>]
            [--cert <path-to-client-certificate>
             --key <path-to-private-key>]
}
```

=== Options

|===
|Option |Long Version | Explanation | Default

| ``-h``   | ``--host``| The MQTT host. | ``localhost``

| ``-V``   | ``--version``| The MQTT version can be set to 3 or 5. | ``MQTT  v.5.0``

| ``-p``  | ``--port``| The MQTT port. | ``1883``

| ``-i``   | ``--identifier`` | A unique client identifier can be defined. | A randomly defined UTF-8 String will be generated.

| ``-d``    |   ``--debug``     | Print info level debug messages to the console. | ``False``

| ``-v``    |   ``--verbose``   | Print detailed debug level messages to the console. | ``False``

| ``-u``   | ``--user`` | A username for authentication can be defined. |

| ``-P``  | ``--password`` | A password for authentication can be defined directly.

If left blank the user will be prompted for the password in console.
|

| ``-c``   | ``--clean`` | Disable clean start if set. | ``True``

| ``-s``    | ``--secure``  | Use the default SSL configuration. | ``False``

| ``-e``  | ``--sessionExpiry`` | Session expiry value in seconds. | ``0`` (No Expiry)

| ``-wt``  | ``--willTopic`` | Topic of the will message.  |

| ``-wq``   | ``--willQualityOfService`` | QoS level of the will message. | ``0``

| ``-wm``  | ``--willPayload`` | Payload of the will message. |

| ``-wr``   | ``--willRetain``  | Retain the will message. | ``False``

| ``-we``   | ``--willMessageExpiryInterval``   | Lifetime of the will message in seconds.

Can be disabled by setting it to ``4_294_967_295``| ``4_294_967_295`` (Disabled)

| ``-wd`` | ``--willDelayInterval`` | Will delay interval in seconds. | ``0``

| ``-wp``  | ``--willPayloadFormatIndicator`` |Payload format can be explicitly specified as ``UTF8`` else it may be ``UNSPECIFIED``. |

| ``-wc``   | ``--willContentType`` |   Description of the will message's content. |

| ``-wrt``  | ``--willResponseTopic`` | Topic Name for a response message.   |

| ``-wcd``  | ``--willCorrelationData`` | Correlation data of the will message  |

| ``-wu``   | ``--willUserProperties``  | User properties of the will message can be defined like

``key=value`` for single pair or ``key1=value1\|key2=value2`` for multiple pairs. |

| | ``--cafile``    | Path to a file containing a trusted CA certificate to enable encrypted certificate based communication. |

|   | ``--capath``  | Path to a directory containing trusted CA certificates to enable encrypted certificate based communication. |

|   | ``--ciphers``  | The supported cipher suites in IANA string format concatenated by the ':' character if more than one cipher should be supported.
e.g ``TLS_CIPHER_1:TLS_CIPHER_2``

See https://www.iana.org/assignments/tls-parameters/tls-parameters.xml for supported cipher suite strings.
|
|   |   ``--tls-version``   |   The TLS version to use -
``TLSv1.1``
``TLSv1.2``
``TLSv1.3``
| ``TLSv1.2``

|   |   ``--cert``  |   The path to the client certificate to use for client-side authentication. |

|   |   ``--key``   |   The path to the client certificate corresponding  private key to use for client-side authentication.    |
|===

=== Examples

Connect a client to myHost on port 1884:

```
hmq> con -h myHost -p 1884
```

Connect a client to the default host on default port using authentication:

```
hmq> con -u username -P password
# Or omit the password to get it prompted
hmq> con -u username -P
Enter value for --password (The password for the client UTF-8 String.):
```

Connect a client with default settings and use it to publish:

```
hmq> con -i myClient
myClient@localhost> pub -t test -m "Hello World"
```

Connect a client with a will message:

```
hmq> con -wt willtopic -wq 2 -wm "Client disconnected ungracefully"
```

Connect a client with SSL using client side and server side authentication with a password encrypted private key:

```
hmq> con --cafile pathToServerCertificate.pem --tls-version TLSv.1.3
         --cert pathToClientCertificate.pem --key pathToClientKey.pem
Enter private key password:
```

== Publish

NOTE: Publish supports all Connect options.
Therefore all Connect options can be used with publish.

NOTE: In Shell-Mode use the <<Publish (with context)>> equivalent.

Publishes a message to one or more topics.

=== Simple Examples

|===
|Command |Explanation

| ``hivemq-cli pub -t test -m "Hello" ``
| Publish the message "Hello" to the test topics with the default settings

| ``hivemq-cli pub -t test1 -t test2 -m "Hello Tests"``
| Publish the message "Hello Tests" on both test topics with the default settings

| ``hivemq-cli pub -t test -m "Hello" -h localhost -p 1884``
| Publish the message "Hello" on localhost:1884
|===

See also ``hivemq-cli pub --help``

=== Synopsis

```
hivemq-cli pub { [[Connect-Option] [Connect-Option]]
                -t <topic> [-t <topic>]...
                -m <message>
                [-q <qos>]...
                [-r]
                [-pc <contentType>]
                [-pd <correlationData>]
                [-pe <messageExpiryInterval>]
                [-pf <payloadFormatIndicator>]
                [-pr <responseTopic>]
                [-pu <publishUserProperties>]
}
```

=== Options

|===

|Option |Long Version | Explanation | Default

| ``-t``   | ``--topic``| The MQTT topic where the message will be published. |
| ``-m``| ``--message`` | The message which will be published on the topic. |
| ``-r``| ``--retain`` | Message will be retained. | ``False``
| ``-q`` | ``--qos`` | Use a defined quality of service level on all topics if only one QoS is specified.

You can define a specific QoS level for every topic. The corresponding QoS levels will be matched in order to the given topics. | ``0``

| ``-pc`` | ``--contentType`` | A description of the content of the publish message. |

| ``-pd`` | ``--correlationData`` | The correlation data of the publish message. |

| ``-pe`` | ``--messageExpiryInterval`` | The lifetime of the publish message in seconds. |

| ``-pf`` | ``--payloadFormatIndicator`` | The payload format indicator of the publish message. |

| ``-pr`` | ``--responseTopic`` | The topic name for the response message of the publish message. |

| ``-pu`` | ``--publishUserProperties``  | The user property of the publish message. Usage: Key=Value, Key1=Value1:Key2=Value2 |

|===

=== Further Examples

Publish a message with default QoS set to Exactly Once:

NOTE: If you only specify one QoS but more than one topic the QoS will be used as default QoS for all topics.

```
$ hivemq-cli pub -t topic1 -t topic2 -q 2
```

Publish a message with a given QoS for each topic. (topic1 will have QoS 0, topic2 QoS 1, topic2 QoS 2):

```
$ hivemq-cli pub -t topic1 -t topic2 -t topic3 -q 0 -q 1 -q 2
```

== Subscribe

NOTE: Subscribe supports all Connect options.
Therefore all Connect options can be used with subscribe.

NOTE: In Shell-Mode use the <<Subscribe (with context)>> equivalent.

Subscribes a client to one or more topics.
If the Subscribe command is not called in Shell-Mode it will block the console by default and write the received publishes to the console.

=== Simple Examples

|===
|Command |Explanation

| ``hivemq-cli sub -t topic``
| Subscribe to a topic on default settings and block the console.

| ``hivemq-cli sub -t test1 -t test2``
| Subscribe to the topics test1 and test2 on default settings and block the console.

| ``hivemq-cli sub -t test -h localhost -p 1884``
| Subscribe to topic test at localhost:1884.
|===

See also ``hivemq-cli sub --help``

=== Synopsis

```
hivemq-cli sub { [[Connect-Option] [Connect-Option]]
                -t <topics> [-t <topics>]...
                [-q <qos>]...
                [-b64]
                [-oc]
                [-of <receivedMessagesFile>]
}
```

=== Options

|===
|Option |Long Version | Explanation | Default

| ``-t``   | ``--topic``| The MQTT topic the client will subscribe to. |
| ``-q`` | ``--qos`` | Use a defined quality of service level on all topics if only one QoS is specified.

You can define a specific QoS level for every topic. The corresponding QoS levels will be matched in order to the given topics. | ``0``
| ``-of``| ``--outputToFile`` | If a file is given print the received publishes to the specified output file. If the file is not present it will be created. |
| ``-oc``| ``--outputToConsole`` | If this flag is set the output will be printed to the console. | ``False`` in Shell-Mode, else ``True``
| ``-b64``| ``--base64``| If set the received publish messages will be base64 encoded. | ``False``


|===

=== Further Examples

Subscribe to one topic with default QoS Exactly Once:

NOTE: If you only specify one QoS but more than one topic the QoS will be used as default QoS for all topics.

```
$ hivemq-cli sub -t topic1 -t topic2 -q 2
```

Subscribe to the given topics with a QoS specified for each: (topic1 will have QoS 0, topic2 QoS 1, topic2 QoS 2)

```
$ hivemq-cli sub -t topic1 -t topic2 -t topic3 -q 0 -q 1 -q 2
```

Subscribe to a topic and output the received publish messages to the file ``publishes.log`` in the current directory:

NOTE: If the file is not created yet it will be created by the CLI. If it is present the received publish messages will be appended to the file.

```
$ hivemq-cli sub -t topic -of publishes.log
```

Subscribe to a topic and output the received publish messages to the file ``publishes.log`` in a specified ``/usr/local/var`` directory:

```
$ hivemq-cli sub -t topic -of /usr/local/var/publishes.log
```

Subscribe to a topic in Shell-Mode and output all the received publish messages to the console:

```
hmq> sub -t topic -oc
```

Subscribe to a topic and output all the received messages in base64 encoding:

```
$ hivemq-cli sub -t topic -b64
```

== Shell

Open HiveMQ-CLI in an interactive shell session.
The shell uses https://github.com/jline/jline3[JLine] for handling console input.
Therefore tab-completion, command-history, password-masking and other familiar shell features are available.

The Shell-Mode is based around a client context driven use case.
Therefore methods like Connect and Disconnect switch the current context of the shell and commands like Publish and Subscribe always relate to the currently active client context.

Example:

```
hivemq-cli shell                # starts the shell

hmq> con -i myClient            # connect client with identifier
myClient> pub -t test -m msg    # publish with new context client
myClient> dis                   # disconnect and remove context
hmq> ...
```

=== Summary

Start interactive shell with:
```
$ hivemq-cli shell
```

In Shell-Mode the following Commands are available **without** an active context:

* <<Connect (in shell)>>
* <<Disconnect>>
* <<Switch>>
* <<List>>
* <<Clear>>

In Shell-Mode the following Commands are available **with** an active context:

* <<Publish (with context)>>
* <<Subscribe (with context)>>
* <<Unsubscribe>>
* <<Disconnect>>
* <<Switch>>
* <<Exit>>
* <<List>>
* <<Clear>>



NOTE: A client is uniquely identified in the CLI by the **version**, **hostname**, **port** and the unique **identifier**.

=== Connect (in shell)

Please refer to <<Connect>> for usage information.

Connect switches the current client context to the newly connected client.

Example:

```
hmq> con -i clientID

clientID@localhost>
```

NOTE: The **--debug** and **--verbose** options are overridden by the default values of the shell.

=== Disconnect

Disconnects a previously connected client.

==== Synopsis (without client context)

```
dis     [-i <identifier>]
        [-h <hostname>]
        [-p <port>]
        [-V <version>]
```

==== Synopsis (with client context):

Disconnects the currently active client context.

```
client-context> dis
```

==== Options:

|===
|Option |Long Version | Explanation | Default

| ``-i``   | ``--identifier``| The unique identifier of a client. |

| ``-h``| ``--host`` | The host the client is connected to. | ``localhost``

| ``-p``| ``--port`` | The port on which the client is connected. | ``1883``

| ``-V`` | ``--version`` |  The MQTT version which the connected client is using. | ``MQTT  v.5.0``

|===

==== Examples:

Connect a client which is identified by myClient and disconnect it afterwards using default settings:

```
hmq> con -i myClient
myClient@localhost> dis
hmq>
```

Connect a client which is identified by myClient on specific settings and disconnect it afterwards:

NOTE: Besides the **identifier** also **version**, **hostname** and **port** have to be given to uniquely identify the client.
If you don't specify these the default settings for these attributes will be used which may lead to unexpected behavior.

```
hmq> con -i myClient -h broker.hivemq.com -V 3
myClient@localhost> exit  # client is still connected
hmq> dis -i myClient -h broker.hivemq.com -V 3
```

=== Publish (with context)

The publish with a context works almost the same as <<Publish>> but it will not create a new connection and publish with a new client.
Instead it uses the currently active context client.

==== Synopsis:

```
clientID> pub   -t <topics> [-t <topics>]...
                -m <message>
                [-q <qos>]...
                [-r]
                [-pc <contentType>]
                [-pd <correlationData>]
                [-pe <messageExpiryInterval>]
                [-pf <payloadFormatIndicator>]
                [-pr <responseTopic>]
                [-pu <publishUserProperties>]
```

NOTE: The default options are the same as in <<Publish>>

==== Options

See <<Publish>>

==== Example

Publish with a client identified with "myClient" to the default settings:

```
hmq> con -i myClient
myClient@localhost> pub -t test -m msg
```

=== Subscribe (with context)

The subscribe with a context subscribes the currently active context client to the given topics.
By default it doesn't block the console like the <<Subscribe>>
without a context does.
To enable this behavior you can use the **-s** option.

==== Synopsis

```
clientID> sub   -t <topics> [-t <topics>]...
                [-q <qos>]...
                [-s]
                [-b64]
                [-oc]
                [-of <receivedMessagesFile>]


```

====  Options

See <<Subscribe>>

|===
|Option |Long Version | Explanation | Default

| ``-s``   | ``--stay``| The subscribe will block the console and wait for publish messages to print.  | ``false``

|===

==== Example:

Subscribe to test topic on default settings (output will be written to Logfile.
See <<Logging>>):

```
hmq> con -i myClient
myClient@localhost> sub -t test
```

Subscribe to test topic on default settings, block console and write received publishes to console:

```
myClient@localhost> pub -t test -m Hello -r
myClient@localhost> sub -t test -s
Hello
...
```

=== Unsubscribe

Unsubscribes the currently active context client from a list of topics.

==== Synopsis

```
unsub   -t <topics> [-t <topics>]...
        [-u <userProperties>]
```

==== Options:

|===
|Option |Long Version | Explanation | Default

| ``-t``   | ``--topic``| A topic from which the client will unsubscribe from. |

| ``-u``| ``--userProperties`` | User properties of the unsubscribe message can be defined like

``key=value`` for single pair or ``key1=value1\|key2=value2`` for multiple pairs. |


|===

==== Examples:

Connect a client which is identified by myClient and subscribe it to two topics afterwards.
Then unsubscribe from one of the two topics:

```
hmq> con -i myClient
myClient@localhost> sub -t topic1 -t topic2
myClient@localhost> unsub -t topic1
hmq>
```

=== Switch

Switches the currently active context client.

==== Synopsis

```
{ hmq | clientID }> switch  [<contextName>]
                            -i <identifier>
                            [-h <host>]
```

==== Parameters

|===
|Parameter Name | Explanation | Examples

| ``contextName``   | The context name of a client consisting of the the client identifier concatenated by a @ with the hostname.
The hostname may be omitted and will be filled with the default host.
| ``myClient@localhost``

``client2@broker.hivemq.com``

``clientID`` (default @localhost will be added)

|===

==== Options

|===
|Option |Long Version | Explanation | Default

| ``-i``   | ``--identifier``| The unique identifier of a client. |

| ``-h``| ``--host`` | The host the client is connected to. | ``localhost``

|===

==== Example

Connect two clients and switch the active context to the first connected client:

```
hmq> con -i client1
client1@localhost> exit
hmq> con -i client2 -h broker.hivemq.com
client2@broker.hivemq.com> switch client1
client1@localhost> switch client2@broker.hivemq.com
client2@broker.hivemq.com>
```

=== Exit

Exits the currently active client context.

==== Synopsis

```
clientID> exit
```

==== Example

```
hmq> con -i client
client@localhost> exit
hmq>
```

=== List

Lists all the connected clients.

==== Synopsis

```
{ hmq | clientID }> ls [-t <sort-by-time>]
                        [-a <all>]

```

==== Options

|===
|Option |Long Version | Explanation | Default

| ``-t``   | ``--time``| Sort the clients by their creation time. | ``False``
| ``-a``    | ``--all`` | Show detailed information about the clients. | ``False``

|===

==== Examples

Connect two clients and list them by default settings:

```
hmq> con -i client1
hmq> con -i client2
hmq> ls
Client-ID            Server-Address
client1              localhost:1883
client2              localhost:1883
```

Connect a client and show detailed information about it:

```
hmq> con -i client
hmq> ls -a
Created-At                     Client-ID            Host                 Port       Server-Address            MQTT version    SSL
2019-08-21T10:47:35.745179     client               localhost            1883       localhost:1883            MQTT_5_0        false
```

NOTE: The list options can be combined in a single command.
So **-at** and **-ta** are valid options.

=== Clear

Clears the terminal screen.

==== Synopsis

```
{ hmq | clientID }> clear
```

==== Example

```
hmq> clear
```

=== Logging

By default the Shell-Model logs all commands in verbose mode to a uniquely named logfile which is placed in a temp directory which is printed out at the start of the shell.

