# HiveMQ client command line tool **mqtt**

## Under Construction! ##

* Mqtt is a command line interface for create and connect MQTT 5 clients, subscribe to topics, publish messages and disconnects client. Auth paket for MQTT 5 clients is also available.
* Mqtt works by default with MQTT 5, but working with MQTT 3 is also possible.
* Mqtt parameters can be read from cmd line or alternatively from a json/yaml file, that contains the description.


This overview covers command line syntax and file description, explains the command operations, and provides common examples.

## Synopsis:

```
$ mqtt [METHOD] URL [ITEM [ITEM]]

```

See also mqtt --help.


=== Methods Overview
The following Methods are supported

```
sub, pub, con, auth(v5), disc
```

=== Specific Methods

==== Interactive MOde
* Mqtt can be started in shell mode, to work interactive.

```
$mqtt shell
mqtt> con -i C1 ...
mqtt> sub -t t1
mqtt> dis -i C1


```

==== File input
* alternatively to parameter all Input can be read from a yaml file with the @<fileName> syntax.
```
$ mqtt sub @/path2my/yamlFile.yml

```


=== Detailed description
==== mqtt con

- Creates a client and connect them. The client can stays connected.
- This is especially useful for the shell mode in addition with further mqtt-packet usage.
- Attributes: Client identifier, Will properties, Will topic, Will payload, User name, password and session state.


.Simple Examples
|===
|Command |Explanation

|mqtt con
|connects an MQTT 5 client at localhost with default port 1883

|mqtt v3 con -h myHost
|connects an MQTT 3.1.1 client at myHost with default port 1883

|mqtt con -p 1884
|connects an MQTT 5 client at localhost with port 1884.
|===

All further attributes are not mandatory.

.Full Syntax

```
mqtt con { @<fileName> |
                -v              {3|5}
                -h              <host>
                -p              <port>
                -i              client identifier
                -u              {<'user name'>}
                -pw             {$|<'password'>| @<fileName>}
                -cs             {0|1}
                -se             {0|1}
                -wt             {$|<'topic'>};
                -wq             {0|1|2|AT_MOST_ONCE|AT_LEAST_ONCE|EXACTLY_ONCE}
                -wm             {$|<'payload'>|@<fileName>};
                -wr             {0|1}
                -we             {[0 - 4_294_967_295]}
                -wd             {[0 - 4_294_967_295]}
                -wp             {UTF8|UTF_8}
                -wc             {<'content description'>}
                -wrt            {$|<'response topic'>}
                -wcd            {<'correlation data'>}
                -wu             {[<'header'='value'> [|<'header'>=<'value'>]*}
                -s              {0|1}
                --cafile        {'filepath'}
                --capath        {'directorypath'}
                --ciphers       {['TLS_ciphersuite'] [:'TLS_ciphersuite']*}
                --tls-version   {'TLS_version'}
                --cert          {'filepath'}
                --key           {'filepath'}
         }
```
|===
|Attribute |long Version | Explanation | default
| con  | connect | Method for connecting a client |
| @  | --file | all information will be read from the file | Not set
| -v   | --version| The MQTT version can be set to 3 or 5. | Version 5 will be used
| -h   | --host| The MQTT host. | localhost will be used
| -p   | --port| The MQTT port. | 1883 will be used
| -i   | --identifier| A unique Client identifier can be defined. | A randomly defined UTF-8 String will be generated.
| -u   | --user | A User name can be defined. | Not set - user name will be empty.
| -pw  | --password | A password can be defined direct or

         $ - via input from console - prompt, or

         @<fileName> - read from file
         | Not set - password will be empty.
| -c   | --clean | Clean State start setting 0 or 1. | Not set - Clean Start is set cs=1
| -se  | --sessionExpiry | Session Expiry value in seconds. | Not set - Session expires after connection is closed se=0
| -wt  | --willTopic |Topic of the Will message can be defined direct or

         $ - via input from console - prompt
         | Not set - no will message will be generated
| -wq   | --willQualityOfService | QoS level of the will message | 0 (AT_MOST_ONCE)
| -wm  | --willPayload |Payload of the Will message can be defined direct or

         $ - via input from console - prompt, or
         @<fileName> - read from file
         | Not set - no will message will be generated
| -wr   | --willRetain  | Will message will be retained |false
| -we   | --willMessageExpiryInterval   |Lifetime of the will message in seconds

Can be disabled by setting it to ```4_294_967_295```|4_294_967_295
| -wd  | --willDelayInterval |Will delay interval in seconds | 0
| -wp  | --willPayloadFormatIndicator |Payload Format can be specified as ```UTF8``` else it may be ``UNSPECIFIED`` | default empty
| -wc   | --willContentType |   Description of the Will Message's content | default empty
| -wrt  | --willResponseTopic | Topic Name for a response message   |   default empty
| -wcd  | --willCorrelationData | Correlation Data of the Will Message  |   default empty
| -wu   | --willUserProperties  | User Properties of the Will Message can be defined like

```key=value``` for single pair or ```key1=value1\|key2=value2``` for multiple pairs | default empty


| -sc | --stayConnected | The client stays connected 0 or 1 |  0 - the client will be disconnected immediately. In shell mode the Client stays connected.
| -s    | --secure  | The client uses the default ssl configuration to communicate with the broker | False
| | --cafile    | Path to a file containing a trusted CA certificate to enable encrypted certificate based communication | default empty
|   | --capath  | Path to a directory containing trusted CA certificates to enable encrypted certificate based communication | default empty
|   | --ciphers  | The supported cipher suites in IANA string format concatenated by the ':' character if more than one cipher should be supported.

See https://www.iana.org/assignments/tls-parameters/tls-parameters.xml for supported cipher suite strings.
 | default empty
|   |   --tls-version   |   The TLS version to use | TLSv1.2
|   |   --cert  |   The path to the client certificate to use for client-side authentication.

NOTE: Currently only self signed certificates are supported. | default empty
|   |   --key   |   The path to the client private key to use for client-side authentication.    | default empty
|===

.Full Example
```
mqtt con -i C1 -u Max -pw $ -sc 1
```
A client with Identifier _C1_ will be connected with a clean start. The user name is set to _Max_, the password will be set directly by the user via cmd line input. After creation and connecting, the connection will stay opened.


**Alternative all client related properties can be read from file**
    
```
mqtt con @<fileName>
```
- connects an MQTT 5 client and reads the properties from the file.


==== mqtt sub

- Subscribes a client to one or more topics.
- The client is connected with the properties described in [mqtt con]

.Examples for setting the URL
|===
|Command |Explanation
| mqtt sub @c1.yaml -t 'topic1' | A client described via file connects localhost and subscribes to topic 'topic1'
| mqtt sub @c1.yaml -t 'topic1','topic2' | A client described via file connects localhost and subscribes to topic 'topic1' and 'topic2'
| mqtt sub @c1.yaml @topics.yaml | A client described via file connects localhost and subscribes to topic 'topic1' and 'topic2'
|===


.Full Syntax

```
mqtt sub    { @<fileName> |
                <Client Settings>
                -t {$|[<topicFilter> [,<topicFilter>]]}
                -q [<0|1|2> [,<0|1|2>]]
            }
```

|===
|Attribute |long Version | Explanation | Default behavior
| sub | subscribe | command to subscribe a client to a list of topics  |
| @  | --file | all information will be read from the file | Not set
| -t | --topic | One or more topics as UTF-8 String, comma separated. Can be defined direct or
        $ - via input from console - prompt, or
        @<fileName> - read from file
        | Mandatory
| -q | --qos |One or more Quality of services as number - can be 0, 1 or 2, comma separated. Can be defined direct or
        $ - via input from console - prompt
        | 0.
|===

.Full Example
```
mqtt sub @con.yaml -t 'my/1/#','my/2/#' -q 0,1
```
An MQTT 5 client described in c1.yaml will be connected and subscribes to the topics that fits to the filter 'my/1/\#'  with qos 0 and 'my/2/\#' with qos 1.


###File Descriptors

As mentioned on top, all details of the commands can be packed into yaml/json files

.Example for con command

```
mqtt:
   _version: 5
   method: con
   client:
    identifier: C1
    user: Max
    password: "$"
    cleanStart: 1
    sessionExpiry: 0
    will:
     properties:
      p:
       - "p1:x1"
       - "p2:x2"
     topic: "/myLastWill"
     payload: "@/path2my/will.yaml"
    stayConnected: 1
```


.Example for subscribe command

```
mqtt:
 method: sub
 client:
    _file: "/path2my/con.yaml"
 topics:
  topic:
   -
   name: topic1
    qos: 0
   -
   name: topic2
    qos: 1
```