name: mqtt-cli

summary: MQTT Client Command Line Interface

description: |
  MQTT CLI is a tool that provides a feature rich command line interface for connecting,
  publishing, subscribing, unsubscribing and disconnecting
  various MQTT clients simultaneously and supports  MQTT 5.0 and MQTT 3.1.1
version: '1.0'

base: core18
grade: stable
confinement: strict

parts:
  mqtt-cli:
    plugin: gradle
    source: .
    stage-packages:
      - default-jre

  exec:
    plugin: dump
    source: snap/local

apps:
  mqtt-cli:
    command: mqtt-cli.sh

    adapter: full
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-$SNAP_ARCH
      PATH: $JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH

