name: Run Snyk monitor on push

on:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      github_ref:
        required: true
        type: string

jobs:
  run-snyk-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Select GitHub ref
        id: select_github_ref
        shell: bash
        run: |
          workflow_call_github_ref=${{ inputs.github_ref }}
          echo "selected_github_ref=${workflow_call_github_ref:-${{ github.ref_name }}}" >> "$GITHUB_OUTPUT"

      - name: Setup Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          distribution: temurin
          java-version: |
            11
            25

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          path: mqtt-cli
          ref: ${{ steps.select_github_ref.outputs.selected_github_ref }}

      - name: Setup Snyk
        uses: snyk/actions/setup@12140f4059e244892ae643824a95459a102120dd # master

      - name: Run Snyk monitor
        shell: bash
        run: >
          snyk monitor --configuration-matching=^runtimeClasspath$ --target-reference=${{ steps.select_github_ref.outputs.selected_github_ref }} --org=hivemq-mqtt-cli
          --project-name=mqtt-cli --remote-repo-url=mqtt-cli --project-lifecycle=development mqtt-cli -d
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
