name: Run Snyk monitor on push

on:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      github_ref:
        required: true
        type: string

jobs:
  run-snyk-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Select GitHub ref
        id: select_github_ref
        shell: bash
        run: |
          workflow_call_github_ref=${{ inputs.github_ref }}
          echo "selected_github_ref=${workflow_call_github_ref:-${{ github.ref_name }}}" >> "$GITHUB_OUTPUT"

      - name: Setup Java
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5
        with:
          distribution: temurin
          java-version: |
            11
            21

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          path: mqtt-cli
          ref: ${{ steps.select_github_ref.outputs.selected_github_ref }}

      - name: Setup Snyk
        uses: snyk/actions/setup@8e119fbb6c251787721d34ba683ed48eba792766 # master

      - name: Run Snyk monitor
        shell: bash
        run: >
          snyk monitor --configuration-matching=^runtimeClasspath$ --target-reference=${{ steps.select_github_ref.outputs.selected_github_ref }} --org=hivemq-mqtt-cli
          --project-name=mqtt-cli --remote-repo-url=mqtt-cli --project-lifecycle=development mqtt-cli -d
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
